### ISSUE TITLE
Create , Update and Delete Subscribed Users

### ISSUE THREAD

**Issue by Ezeko** [hngi/expenseng#274]
As an admin, I should be able to create, edit and delete subscribed users
![Screenshot_2020-07-20-15-40-11-825_com android chrome](https://user-images.githubusercontent.com/31517324/88000932-c25f1c00-caf6-11ea-9df9-314390ec2165.jpg)

**Comment by Ezeko** [comment]
@EphraimDev

**Comment by EphraimDev** [comment]
Approved

**Comment by Ezeko** [comment]
#278

**Comment by EphraimDev** [comment]
Some edge cases to consider 
1. I tried editing a row and I successfully subscribed for a nonsense report type. Shouldn't that report type be a select tag so that the right report type is selected? A little spelling issue can be disastrous 

2. I successfully subscribed for a particular report type twice using same email. I do not think this is good practice. 

3. Will users get an email to confirm subscription? I think you should consider that.

**Comment by Ezeko** [comment]
Noted

**Comment by Ezeko** [comment]
#280 
@EphraimDev changes effected

**Comment by Ezeko** [comment]
#316 
Email now sending @EphraimDev

**Comment by Ezeko** [comment]
#327 
Add subscribexpenseng@gmail.com as sender email address

**Comment by Ezeko** [comment]
@EphraimDev this is live, we can test this now.

**Comment by Ezeko** [comment]
#373

**Comment by Ezeko** [comment]
@EphraimDev  this is working with email template. In my new push #430
